#!/bin/bash

# chkconfig: 2345 40 60
# description: start and stop the Yum Repo Daemon

### BEGIN INIT INFO
# Provides:			
# Required-Start:	
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Yum Repo Daemon
# Description:			Yum Repo Daemon
### END INIT INFO

# where should the pid file live
PIDFILE=${PIDFILE:=/var/run/yum-repo-server/yum-repo-server.pid}
PROJECTPATH=/opt/yum_repo_server

# source in some helper scripts
. /etc/rc.d/init.d/functions

check_for_pidfile() {
	if [ -f $PIDFILE ]; then
		echo "YUM Repo Daemon seems to be running since the pidfile exists"
		failure
		echo
		exit 1
	fi
}


start() {
	echo "Starting YUM Repo Daemon: "
	check_for_pidfile
	/usr/bin/python ${PROJECTPATH}/daemon/schedulerDaemon.py start --pidfile=$PIDFILE
}

stop() {
	echo "Stopping YUM Repo Daemon: "
	if [ ! -e $PIDFILE ]
	then
		echo "Stop failed. Pidfile does not exist. Was the service started before?"
		return 1
	fi
	
	processId=`cat $PIDFILE`
	/usr/bin/python ${PROJECTPATH}/daemon/schedulerDaemon.py stop --pidfile=$PIDFILE
	
	for i in {1..60} 
	do
		kill -0 $processId 2>/dev/null
		if [ $? -ne 0 ]
		then 
			return 0
		fi
		sleep 1
	done
	echo "Stop failed. Process is still running after 60 seconds."
	return 1
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop && start
	;;

  status)
	status -p $PIDFILE yum_repo_daemon
	;;
	
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac
